### PR TITLE
Workflow updates

### PR DESCRIPTION
**Pull request by TheGiraffe3**
Upgrades the spellcheck to a better version (the one Endless Sky uses).
Fixes some typos.

Adds a new workflow to check the plugins and generate error messages if, say, you're missing a ` sign. I've found it useful.

I added all of the Isaac Wirth, Aline Mai, and Enver Diefenbach lines to `.codespell.exclude` instead of just putting them in `.codespell.words.exclude`, because the names could be typos (I suppose the word Ender won't be used very much, but you know how it goes).

### CODE REVIEW

**Comment by zuckung** [comment]
btw, the Overlayed part of command buttons is a copy and past from thewierdnut. maybe it is meant in a more programmed language, like overlay'ed. not sure about this.

and i m aware of 2 script errors currently in the plugins, i m checking the errorlog a lot. unfortunately i have to fix these 2 errors then, wanted to wait for more content updates^^ but ok, it will prevent future errors.

the exclude of whole lines/phrases is a nice idea.

**Comment by zuckung** [comment]
the script error workflow didn't find the 2 errors?
planet.map has a wrong setting up a condition in the last mission. and jump.gates has a wrong government.
so what does that worklow do? the endlesssky.exe -p? if it just checks for ` , then its not really helpful.

**Comment by TheGiraffe3** [comment]
Hmm, it should be taking the error log from the game and uploading it.
That worked for Omnis when there was a wrong outfitter...

**Comment by TheGiraffe3** [comment]
https://github.com/TheGiraffe3/-Omnis/actions/runs/11031100746/job/30637134173
So it did detect some errors in one version...
I'm thinking it might be because of using -, maybe Windows has trouble with that?
So if you could approve the workflows again, we'll see if this works.

**Comment by zuckung** [comment]
nope doesn't work

**Comment by zuckung** [comment]
and i don't see the part where my plugins are involed

Expand-Archive ${{ env.CONTINUOUS }} -DestinationPath endless-sky -Force
        cd .\endless-sky
        mkdir plugins
        cd .\plugins
        mkdir myplugins

shouldnt it be like 
copy myplugins/* ./endless-sky/plugins/ 
not sure about /\

**Comment by TheGiraffe3** [comment]
Hmm, I don't understand this.
With the exact same workflow as Omnis, this shows nothing; while...https://github.com/TheGiraffe3/-Omnis/actions/runs/11912719990/job/33196918626

**Comment by TheGiraffe3** [comment]
That's really strange.

**Comment by zuckung** [comment]
must be a path problem, so remove that workflow. think i have a good overview of s ript errors.

**Comment by TheGiraffe3** [comment]
Yeah, I'm not sure what the problem there would be.

**Comment by zuckung** [comment]
so merging now?

**Comment by TheGiraffe3** [comment]
Happy to help.

**Comment by TheGiraffe3** [comment]
Hmm, realized what the problem was: Endless Sky checks files in the "data" folder; which this repository doesn't have; and so you don't get any errors.
Not sure it's something easily fixable without drastically altering the repository's structure, but it's nice to know the reason.

**Comment by zuckung** [comment]
yep thought of that, but still don't know how the data folder of "normal" repos fit that criteria, since they are still positioned outside of ./endless-sky/plugins/ .

**Comment by TheGiraffe3** [comment]
It runs the game and reads the plugins, throwing their errors. Because you've got the plugins inside another folder, it didn't work.

**Comment by zuckung** [comment]
but how does the game know where the data folder is? the game runs in root dir, in the script are just new folders created. i didn't  see anything setting up a pointer to the right folders. that's the mystery here^^

**Pull request merged**
